# -*- coding: utf-8 -*-
"""esg2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dbLUjXaYydinPvVJiODjzS2CQYLRYlH
"""

import json, torch, warnings
import pandas as pd
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertModel, get_linear_schedule_with_warmup
from sklearn.metrics import f1_score
from sklearn.model_selection import KFold

warnings.filterwarnings('ignore')

# ============================================================
# Step 1: 超參數與權重設定
# ============================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"目前使用的硬體加速裝置: {device}")

MODEL_NAME = "google-bert/bert-base-chinese"
MAX_LEN = 512
BATCH_SIZE = 16
EPOCHS = 10
LR = 2e-5
N_SPLITS = 5
SEED = 42
RDROP_ALPHA = 1

EVAL_FIELDS = {
    "promise_status": ["Yes", "No"],
    "verification_timeline": ["already", "within_2_years", "between_2_and_5_years", "more_than_5_years", "N/A"],
    "evidence_status": ["Yes", "No", "N/A"],
    "evidence_quality": ["Clear", "Not Clear", "Misleading", "N/A"]
}
FIELD_WEIGHTS = {"promise_status": 0.2, "verification_timeline": 0.15, "evidence_status": 0.3, "evidence_quality": 0.35}
label2id = {field: {label: i for i, label in enumerate(labels)} for field, labels in EVAL_FIELDS.items()}
id2label = {field: {i: label for i, label in enumerate(labels)} for field, labels in EVAL_FIELDS.items()}

WEIGHTS = {
    'promise_status': None,
    'verification_timeline': None,
    'evidence_status': None,
    'evidence_quality': None
}

# ============================================================
# Step 2: 改用 JSON 安全載入（徹底避開 CSV 編碼與引號地雷）
# ============================================================
print("⏳ 正在安全載入 JSON 資料集...")

with open("vpesg_4k_train_1000.json", "r", encoding="utf-8") as f:
    train_list = json.load(f)

with open("vpesg4k_val_1000.json", "r", encoding="utf-8") as f:
    val_list = json.load(f)

with open("vpesg4k_test_2000.json", "r", encoding="utf-8") as f:
    test_list = json.load(f)

# 統一微調清洗標籤資料
for data_list in [train_list, val_list]:
    for item in data_list:
        if item.get('verification_timeline') == 'longer_than_5_years':
            item['verification_timeline'] = 'more_than_5_years'
        for f in EVAL_FIELDS:
            if item.get(f) is None or item[f] == "":
                item[f] = 'N/A'

# 合併 Train & Val 做 5-Fold 最大化泛化
all_train_data = train_list + val_list
all_test_data = test_list

print(f"✅ 載入成功！訓練大池總數: {len(all_train_data)} 筆, 測試集總數: {len(all_test_data)} 筆")

# ============================================================
# Step 3: 模型與對抗訓練類別定義
# ============================================================
class FGM():
    def __init__(self, model):
        self.model = model
        self.backup = {}
    def attack(self, epsilon=1.0, emb_name='word_embeddings'):
        for name, param in self.model.named_parameters():
            if param.requires_grad and emb_name in name:
                self.backup[name] = param.data.clone()
                norm = torch.norm(param.grad)
                if norm != 0 and not torch.isnan(norm):
                    param.data.add_(epsilon * param.grad / norm)
    def restore(self, emb_name='word_embeddings'):
        for name, param in self.model.named_parameters():
            if param.requires_grad and emb_name in name:
                param.data = self.backup[name]
        self.backup = {}

class MultiTaskBERT(nn.Module):
    def __init__(self, num_labels_dict):
        super().__init__()
        self.bert = BertModel.from_pretrained(MODEL_NAME, output_hidden_states=True)
        hidden_size = self.bert.config.hidden_size
        self.layer_weights = nn.Parameter(torch.ones(12))
        self.dropout = nn.Dropout(0.3)
        self.classifiers = nn.ModuleDict({f: nn.Linear(hidden_size, n) for f, n in num_labels_dict.items()})

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        all_hidden_states = outputs.hidden_states[1:]
        weights = F.softmax(self.layer_weights, dim=0)
        out = sum(w * h for w, h in zip(weights, all_hidden_states))
        pooled = out[:, 0, :]
        return {f: clf(self.dropout(pooled)) for f, clf in self.classifiers.items()}

# ============================================================
# Step 4: 優化器與 Dataset 建立
# ============================================================
def get_optimizer_params(model, base_lr):
    param_optimizer = list(model.named_parameters())
    no_decay = ['bias', 'LayerNorm.bias', 'LayerNorm.weight']
    optimizer_grouped_parameters = []
    for i in range(12):
        layers_params = {
            'params': [p for n, p in param_optimizer if f'bert.encoder.layer.{i}.' in n and not any(nd in n for nd in no_decay)],
            'weight_decay': 0.02, 'lr': base_lr * (0.95 ** (12 - i))
        }
        optimizer_grouped_parameters.append(layers_params)
    other_params = {'params': [p for n, p in param_optimizer if 'bert.encoder.layer' not in n], 'weight_decay': 0.02, 'lr': base_lr}
    optimizer_grouped_parameters.append(other_params)
    return optimizer_grouped_parameters

def calculate_all_metrics(gts, preds):
    task_scores = {}
    weighted_f1 = 0.0
    for f in EVAL_FIELDS:
        f1 = f1_score([d[f] for d in gts], [p[f] for p in preds], average="macro", zero_division=0)
        task_scores[f] = f1
        weighted_f1 += f1 * FIELD_WEIGHTS[f]
    return weighted_f1, task_scores

tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)
#tokenizer.truncation_side = 'left'

class ESGDataset(Dataset):
    def __init__(self, data, tokenizer, label2id, is_test=False):
        self.data, self.tokenizer, self.label2id, self.is_test = data, tokenizer, label2id, is_test
    def __len__(self): return len(self.data)
    def __getitem__(self, idx):
        s = self.data[idx]
        enc = self.tokenizer(s['data'], truncation=True, max_length=MAX_LEN, padding='max_length', return_tensors='pt')
        item = {'input_ids': enc['input_ids'].squeeze(0), 'attention_mask': enc['attention_mask'].squeeze(0)}
        if not self.is_test:
            item['labels'] = {f: torch.tensor(self.label2id[f][s[f]], dtype=torch.long) for f in EVAL_FIELDS}
        return item

# ============================================================
# Step 5: 開始 5-Fold 交叉驗證訓練
# ============================================================
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
all_fold_weighted_scores = []
all_data_np = np.array(all_train_data)

for fold, (train_idx, val_idx) in enumerate(kf.split(all_data_np)):
    print("\n" + "="*50)
    print(f"🚀 Fold {fold+1} 啟動 (使用 JSON 安全大資料池)...")
    print("="*50)

    train_d, val_d = all_data_np[train_idx].tolist(), all_data_np[val_idx].tolist()
    train_loader = DataLoader(ESGDataset(train_d, tokenizer, label2id), batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(ESGDataset(val_d, tokenizer, label2id), batch_size=BATCH_SIZE, shuffle=False)

    model = MultiTaskBERT({f: len(l) for f, l in EVAL_FIELDS.items()}).to(device)
    fgm = FGM(model)
    swa_model = torch.optim.swa_utils.AveragedModel(model)
    optimizer = torch.optim.AdamW(get_optimizer_params(model, LR))
    scheduler = get_linear_schedule_with_warmup(optimizer, int(0.1*len(train_loader)*EPOCHS), len(train_loader)*EPOCHS)

    for epoch in range(EPOCHS):
        model.train()
        total_loss = 0

        for batch_idx, batch in enumerate(train_loader):
            optimizer.zero_grad()
            ids, mask = batch["input_ids"].to(device), batch["attention_mask"].to(device)
            labels = {f: batch["labels"][f].to(device) for f in EVAL_FIELDS}

            logits1, logits2 = model(ids, mask), model(ids, mask)
            loss = 0
            for f in EVAL_FIELDS:
                criterion = nn.CrossEntropyLoss(weight=WEIGHTS.get(f), label_smoothing=0.08)
                ce_loss = (criterion(logits1[f], labels[f]) + criterion(logits2[f], labels[f])) / 2
                kl_loss = (F.kl_div(F.log_softmax(logits1[f], -1), F.softmax(logits2[f], -1), reduction='batchmean') +
                           F.kl_div(F.log_softmax(logits2[f], -1), F.softmax(logits1[f], -1), reduction='batchmean')) / 2
                loss += (1.5 if f == "evidence_quality" else 1.0) * (ce_loss + RDROP_ALPHA * kl_loss)

            loss.backward()

            if fgm:
                fgm.attack()
                logits_adv = model(ids, mask)
                loss_adv = sum(nn.CrossEntropyLoss(weight=WEIGHTS.get(f), label_smoothing=0.08)(logits_adv[f], labels[f]) for f in EVAL_FIELDS)
                loss_adv.backward()
                fgm.restore()

            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            total_loss += loss.item()

            if batch_idx % 15 == 0:
                print(f"  [Epoch {epoch+1:02d}/{EPOCHS:02d}] Batch {batch_idx:03d}/{len(train_loader):03d} | Loss: {loss.item():.4f}")

        if epoch >= int(EPOCHS * 0.75):
            swa_model.update_parameters(model)
            print(f"  ✨ Epoch {epoch+1} 結束 | 平均 Loss: {total_loss/len(train_loader):.4f} (已更新 SWA)")
        else:
            print(f"  ✨ Epoch {epoch+1} 結束 | 平均 Loss: {total_loss/len(train_loader):.4f}")

    print(f"  🔍 正在評估 Fold {fold+1} 的驗證集分數...")
    swa_model.eval()
    preds = []
    with torch.no_grad():
        for b in val_loader:
            out = swa_model(b["input_ids"].to(device), b["attention_mask"].to(device))
            for i in range(b["input_ids"].size(0)):
                preds.append({f: id2label[f][out[f][i].argmax().item()] for f in EVAL_FIELDS})

    weighted_f1, task_f1s = calculate_all_metrics(val_d, preds)
    torch.save(swa_model.module.state_dict(), f"model_fold_{fold}.pt")

    print(f"✅ Fold {fold+1} 內部交叉驗證報告:")
    print(f"   [加權 F1 總分]: {weighted_f1:.5f}")
    all_fold_weighted_scores.append(weighted_f1)

print(f"\n🔥 5-Fold 平均交叉驗證 OOF 分數: {np.mean(all_fold_weighted_scores):.5f}")

# ============================================================
# Step 6: 預測測試集並輸出
# ============================================================
print(f"\n🏆 開始對真正的測試集 ({len(all_test_data)} 筆) 進行 5-Fold 模型集成預測...")
models = []
for i in range(N_SPLITS):
    m = MultiTaskBERT({f: len(l) for f, l in EVAL_FIELDS.items()}).to(device)
    m.load_state_dict(torch.load(f"model_fold_{i}.pt"))
    m.eval()
    models.append(m)

test_loader = DataLoader(ESGDataset(all_test_data, tokenizer, label2id, is_test=True), batch_size=BATCH_SIZE, shuffle=False)
test_preds = {f: [] for f in EVAL_FIELDS}
test_ids = [item['id'] for item in all_test_data]

with torch.no_grad():
    for batch in test_loader:
        batch_size_current = batch["input_ids"].size(0)
        probs_accum = {f: torch.zeros((batch_size_current, len(EVAL_FIELDS[f]))).to(device) for f in EVAL_FIELDS}

        for m in models:
            out = m(batch["input_ids"].to(device), batch["attention_mask"].to(device))
            for f in EVAL_FIELDS:
                probs_accum[f] += torch.softmax(out[f], dim=-1)

        for f in EVAL_FIELDS:
            best_ids = probs_accum[f].argmax(dim=-1).cpu().numpy()
            for b_id in best_ids:
                test_preds[f].append(id2label[f][b_id])

# ============================================================
# Step 7: 生成最終提交的 CSV 檔案
# ============================================================
submission_df = pd.DataFrame({
    "id": test_ids,
    "promise_status": test_preds["promise_status"],
    "verification_timeline": test_preds["verification_timeline"],
    "evidence_status": test_preds["evidence_status"],
    "evidence_quality": test_preds["evidence_quality"]
})

submission_df.to_csv("my_submission.csv", index=False)
print("\n🎉 恭喜！測試集預測完成！已成功匯出符合格式的提交檔案: 'my_submission.csv'")
print(submission_df.head())